#!/usr/bin/env sh

# yabai -m config layout bsp
# yabai -m config top_padding 5
# yabai -m config bottom_padding 5
# yabai -m config left_padding 5
# yabai -m config right_padding 5
# yabai -m config window_gap 5

# Do not manage any windows by default
# yabai -m rule --add app=".*" manage=off

